name: Ping Backend Every Minute

on:
  schedule:
    - cron: '* * * * *'  # Every 5 minutes (UTC)
  workflow_dispatch:       # Allows you to manually run it from GitHub UI

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping your backend
        run: |
          curl -sSf https://hackon-backend.onrender.com/api/health || echo "Ping failed"
